name: "💡 Submit an Idea"
description: "Propose a new idea for this project"
title: "[Idea]: "
labels: ["idea", "under-review"]
body:
  - type: input
    id: idea_title
    attributes:
      label: Idea Title
      placeholder: "A short, clear name for your idea"
    validations:
      required: true

  - type: textarea
    id: idea_description
    attributes:
      label: Idea Description
      placeholder: "Explain the idea. What should be built? Why is it useful?"
    validations:
      required: true
